import { WorkspaceSample } from "../core/domain/analyze";

export const WORKSPACE_SAMPLES: WorkspaceSample[] = [
  {
    id: "sample-1",
    fileName: "ItronPage3.jpeg",
    imageUrl: "/images/ItronPage3.jpeg",
    mockResponse: {
      meter_type: "Digital",
      detected_format: "itron digital index screen page",
      correct_v_scm: "12,450.3",
      line_v_m3: "12,140.1",
      pressure_bar: "2.415",
      temperature_c: "22.5",
      correction_factor: "1.0256",
      turbine_v_m3: "12,135.8",
      qm_m3_h: "145.2",
      qb_sm3_h: "148.9",
      pulse_weight: "1.0",
    },
  },
  {
    id: "sample-2",
    fileName: "testpic.png",
    imageUrl: "/images/testpic.png",
    mockResponse: {
      meter_type: "Analog",
      detected_format: "analog mechanical drum index",
      correct_v_scm: null,
      line_v_m3: "00,342.8",
      pressure_bar: null,
      temperature_c: null,
      correction_factor: null,
      turbine_v_m3: "00,342.8",
      qm_m3_h: null,
      qb_sm3_h: null,
      pulse_weight: null,
    },
  },
  {
    id: "sample-3",
    fileName: "test2.jpg",
    imageUrl: "/images/test2.jpg",
    mockResponse: {
      meter_type: "Digital",
      detected_format: "digital screen index value page",
      correct_v_scm: "84,920.1",
      line_v_m3: "79,040.2",
      pressure_bar: "15.420",
      temperature_c: "28.1",
      correction_factor: "1.0743",
      turbine_v_m3: null,
      qm_m3_h: "850.4",
      qb_sm3_h: "913.6",
      pulse_weight: null,
    },
  },
  {
    id: "sample-4",
    fileName: "test3.jpg",
    imageUrl: "/images/test3.jpg",
    mockResponse: {
      meter_type: "Digital",
      detected_format: "digital screen flow parameters",
      correct_v_scm: null,
      line_v_m3: null,
      pressure_bar: "5.120",
      temperature_c: "24.0",
      correction_factor: "1.0112",
      turbine_v_m3: null,
      qm_m3_h: "220.0",
      qb_sm3_h: "222.4",
      pulse_weight: null,
    },
  },
  {
    id: "sample-5",
    fileName: "test4.jpeg",
    imageUrl: "/images/test4.jpeg",
    mockResponse: {
      meter_type: "Analog",
      detected_format: "analog drum dial counter",
      correct_v_scm: null,
      line_v_m3: "41,200.0",
      pressure_bar: null,
      temperature_c: null,
      correction_factor: null,
      turbine_v_m3: null,
      qm_m3_h: null,
      qb_sm3_h: null,
      pulse_weight: "10.0",
    },
  },
  {
    id: "sample-6",
    fileName: "test5.jpg",
    imageUrl: "/images/test5.jpg",
    mockResponse: {
      meter_type: "Digital",
      detected_format: "digital screen index value page",
      correct_v_scm: null,
      line_v_m3: null,
      pressure_bar: "9.656",
      temperature_c: "25",
      correction_factor: "9.3648",
      turbine_v_m3: null,
      qm_m3_h: "477",
      qb_sm3_h: "4,467.4",
      pulse_weight: null,
    },
  },
  {
    id: "sample-7",
    fileName: "test6.jpg",
    imageUrl: "/images/test6.jpg",
    mockResponse: {
      meter_type: "Digital",
      detected_format: "digital screen simple layout",
      correct_v_scm: "3,124.5",
      line_v_m3: null,
      pressure_bar: "1.013",
      temperature_c: "20.0",
      correction_factor: "1.0000",
      turbine_v_m3: null,
      qm_m3_h: "5.4",
      qb_sm3_h: "5.4",
      pulse_weight: null,
    },
  },
  {
    id: "sample-8",
    fileName: "test7.jpg",
    imageUrl: "/images/test7.jpg",
    mockResponse: {
      meter_type: "Analog",
      detected_format: "analog gas volume index",
      correct_v_scm: null,
      line_v_m3: "00,180.2",
      pressure_bar: null,
      temperature_c: null,
      correction_factor: null,
      turbine_v_m3: "00,180.2",
      qm_m3_h: null,
      qb_sm3_h: null,
      pulse_weight: null,
    },
  },
];
